In [1]:
%reload_ext nb_black

In [2]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns


pd.options.display.max_columns = 999
pd.options.display.max_rows = 99

In [3]:
def missingness_summary(df, print_log=False, sort="none"):
    summary = df.apply(lambda x: x.isna().sum() / x.shape[0])

    if print_log == True:
        if sort == "none":
            print(summary)
        elif sort == "ascending":
            print(summary.sort_values())
        elif sort == "descending":
            print(summary.sort_values(ascending=False))
        else:
            print("Invalid value for sort parameter.")

    return summary

In [4]:
df = pd.read_csv("data/human_trafficking.csv")

C:\Users\dgump\AppData\Roaming\Python\Python37\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (54) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48801 entries, 0 to 48800
Data columns (total 63 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   yearOfRegistration                      48801 non-null  int64
 1   Datasource                              48801 non-null  object
 2   gender                                  48801 non-null  object
 3   ageBroad                                48801 non-null  object
 4   majorityStatus                          48801 non-null  object
 5   majorityStatusAtExploit                 48801 non-null  object
 6   majorityEntry                           48801 non-null  object
 7   citizenship                             48801 non-null  object
 8   meansOfControlDebtBondage               48801 non-null  int64
 9   meansOfControlTakesEarnings             48801 non-null  int64
 10  meansOfControlRestrictsFinancialAccess  48801 non-null  int64
 11  meansOfControlThreats                   48801 non-null  int64
 12  meansOfControlPsychologicalAbuse        48801 non-null  int64
 13  meansOfControlPhysicalAbuse             48801 non-null  int64
 14  meansOfControlSexualAbuse               48801 non-null  int64
 15  meansOfControlFalsePromises             48801 non-null  int64
 16  meansOfControlPsychoactiveSubstances    48801 non-null  int64
 17  meansOfControlRestrictsMovement         48801 non-null  int64
 18  meansOfControlRestrictsMedicalCare      48801 non-null  int64
 19  meansOfControlExcessiveWorkingHours     48801 non-null  int64
 20  meansOfControlUsesChildren              48801 non-null  int64
 21  meansOfControlThreatOfLawEnforcement    48801 non-null  int64
 22  meansOfControlWithholdsNecessities      48801 non-null  int64
 23  meansOfControlWithholdsDocuments        48801 non-null  int64
 24  meansOfControlOther                     48801 non-null  int64
 25  meansOfControlNotSpecified              48801 non-null  int64
 26  meansOfControlConcatenated              48801 non-null  object
 27  isForcedLabour                          48801 non-null  int64
 28  isSexualExploit                         48801 non-null  int64
 29  isOtherExploit                          48801 non-null  int64
 30  isSexAndLabour                          48801 non-null  int64
 31  isForcedMarriage                        48801 non-null  int64
 32  isForcedMilitary                        48801 non-null  int64
 33  isOrganRemoval                          48801 non-null  int64
 34  isSlaveryAndPractices                   48801 non-null  int64
 35  typeOfExploitConcatenated               48801 non-null  object
 36  typeOfLabourAgriculture                 48801 non-null  int64
 37  typeOfLabourAquafarming                 48801 non-null  int64
 38  typeOfLabourBegging                     48801 non-null  int64
 39  typeOfLabourConstruction                48801 non-null  int64
 40  typeOfLabourDomesticWork                48801 non-null  int64
 41  typeOfLabourHospitality                 48801 non-null  int64
 42  typeOfLabourIllicitActivities           48801 non-null  int64
 43  typeOfLabourManufacturing               48801 non-null  int64
 44  typeOfLabourMiningOrDrilling            48801 non-null  int64
 45  typeOfLabourPeddling                    48801 non-null  int64
 46  typeOfLabourTransportation              48801 non-null  int64
 47  typeOfLabourOther                       48801 non-null  int64
 48  typeOfLabourNotSpecified                48801 non-null  int64
 49  typeOfLabourConcatenated                48801 non-null  object
 50  typeOfSexProstitution                   48801 non-null  int64
 51  typeOfSexPornography                    48801 non-null  int64
 52  typeOfSexRemoteInteractiveServices      48801 non-null  int64
 53  typeOfSexPrivateSexualServices          48801 non-null  int64
 54  typeOfSexConcatenated                   48801 non-null  object
 55  isAbduction                             48801 non-null  int64
 56  RecruiterRelationship                   48801 non-null  object
 57  CountryOfExploitation                   48801 non-null  object
 58  recruiterRelationIntimatePartner        48801 non-null  int64
 59  recruiterRelationFriend                 48801 non-null  int64
 60  recruiterRelationFamily                 48801 non-null  int64
 61  recruiterRelationOther                  48801 non-null  int64
 62  recruiterRelationUnknown                48801 non-null  int64
dtypes: int64(50), object(13)
memory usage: 23.5+ MB

In [6]:
df.sample(20)

,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship,meansOfControlDebtBondage,meansOfControlTakesEarnings,meansOfControlRestrictsFinancialAccess,meansOfControlThreats,meansOfControlPsychologicalAbuse,meansOfControlPhysicalAbuse,meansOfControlSexualAbuse,meansOfControlFalsePromises,meansOfControlPsychoactiveSubstances,meansOfControlRestrictsMovement,meansOfControlRestrictsMedicalCare,meansOfControlExcessiveWorkingHours,meansOfControlUsesChildren,meansOfControlThreatOfLawEnforcement,meansOfControlWithholdsNecessities,meansOfControlWithholdsDocuments,meansOfControlOther,meansOfControlNotSpecified,meansOfControlConcatenated,isForcedLabour,isSexualExploit,isOtherExploit,isSexAndLabour,isForcedMarriage,isForcedMilitary,isOrganRemoval,isSlaveryAndPractices,typeOfExploitConcatenated,typeOfLabourAgriculture,typeOfLabourAquafarming,typeOfLabourBegging,typeOfLabourConstruction,typeOfLabourDomesticWork,typeOfLabourHospitality,typeOfLabourIllicitActivities,typeOfLabourManufacturing,typeOfLabourMiningOrDrilling,typeOfLabourPeddling,typeOfLabourTransportation,typeOfLabourOther,typeOfLabourNotSpecified,typeOfLabourConcatenated,typeOfSexProstitution,typeOfSexPornography,typeOfSexRemoteInteractiveServices,typeOfSexPrivateSexualServices,typeOfSexConcatenated,isAbduction,RecruiterRelationship,CountryOfExploitation,recruiterRelationIntimatePartner,recruiterRelationFriend,recruiterRelationFamily,recruiterRelationOther,recruiterRelationUnknown
34100,2016,Hotline,Female,21--23,Adult,Minor,-99,US,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,1,-99,-99,0,Restricts movement;Withholds necessities,0,1,0,0,-99,-99,-99,-99,Sexual exploitation,0,0,0,0,0,0,0,0,0,0,0,0,0,-99,1,0,0,0,Prostitution,0,Not Specified,US,-99,-99,-99,-99,1
21219,2016,Case Management,Female,-99,-99,-99,-99,PH,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,Forced labour,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,Domestic work,-99,-99,-99,-99,-99,-99,-99,-99,0,0,0,0,1
28242,2016,Case Management,Female,-99,-99,-99,-99,PH,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,0,0,0,0,1
39214,2017,Case Management,Male,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,0,0,0,0,1
7536,2010,Case Management,Female,24--26,Adult,-99,-99,CO,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,EC,0,0,0,0,1
24903,2016,Case Management,Female,-99,-99,-99,-99,PH,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,Other,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,0,0,0,0,1
18430,2015,Case Management,Male,48+,Adult,-99,Adult,MM,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,1,0,0,0,0,0,0,-99,Forced labour,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,0,-99,-99,-99,-99,0,-99,ID,0,0,0,0,1
36496,2017,Case Management,Female,0--8,Minor,-99,-99,MD,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,MD,0,0,0,0,1
1021,2002,Case Management,Female,-99,-99,-99,-99,CO,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,0,1,0,0,-99,0,0,-99,Sexual exploitation,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,0,0,0,0,1
19468,2015,Hotline,Female,9--17,Minor,Minor,-99,00,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,0,Psychoactive substances,0,1,0,0,-99,-99,-99,-99,Sexual exploitation,0,0,0,0,0,0,0,0,0,0,0,0,0,-99,1,0,0,0,Prostitution,-99,Other,US,0,0,0,1,0
47911,2018,Hotline,Female,9--17,Minor,Minor,-99,00,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,Not specified,0,1,0,0,-99,-99,-99,-99,Sexual exploitation,0,0,0,0,0,0,0,0,0,0,0,0,0,-99,-99,-99,-99,-99,-99,-99,Not Specified,US,-99,-99,-99,-99,1
21900,2016,Case Management,Female,-99,-99,-99,-99,PH,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,Forced labour,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,Domestic work,-99,-99,-99,-99,-99,-99,Family/Relative,PH,0,0,1,0,0
24656,2016,Case Management,Female,-99,-99,-99,-99,PH,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,Other,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,Family/Relative,-99,0,0,1,0,0
47774,2018,Hotline,Female,9--17,Minor,Minor,-99,00,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,0,Psychological abuse,0,1,0,0,-99,-99,-99,-99,Sexual exploitation,0,0,0,0,0,0,0,0,0,0,0,0,0,-99,-99,-99,-99,-99,-99,0,Family/Relative,US,0,0,1,0,0
15387,2014,Case Management,Male,30--38,Adult,-99,-99,UA,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,UA,0,0,0,0,1
18379,2015,Case Management,Male,48+,Adult,-99,Adult,BY,-99,1,-99,1,1,1,-99,-99,-99,1,-99,1,-99,-99,-99,1,-99,0,Excessive working hours;Physical Abuse;Psychol...,1,0,0,0,0,0,0,-99,Forced labour,0,0,0,1,0,0,0,0,0,0,0,0,0,Construction,0,-99,-99,-99,-99,0,Friend/Acquaintance,RU,0,1,0,1,0
27797,2016,Case Management,Female,-99,-99,-99,-99,PH,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,Slavery and similar practices,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,0,0,0,0,1
5417,2007,Case Management,Female,39--47,Adult,-99,-99,UA,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,1,0,0,0,0,0,0,-99,Forced labour,0,0,0,0,0,0,0,0,0,0,0,0,0,-99,0,-99,-99,-99,-99,0,-99,AT,0,0,0,0,1
25610,2016,Case Management,Female,-99,-99,-99,-99,PH,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,Other,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,0,0,0,0,1
21730,2016,Case Management,Female,-99,-99,-99,-99,PH,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,Forced labour,-99,-99,-99,-99,1,-99,-99,-99,-99,-99,-99,-99,-99,Domestic work,-99,-99,-99,-99,-99,-99,-99,PH,0,0,0,0,1

In [7]:
df = df.replace(to_replace=-99, value=np.nan)
df = df.replace(to_replace="-99", value=np.nan)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48801 entries, 0 to 48800
Data columns (total 63 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   yearOfRegistration                      48801 non-null  int64
 1   Datasource                              48801 non-null  object
 2   gender                                  48801 non-null  object
 3   ageBroad                                36439 non-null  object
 4   majorityStatus                          36439 non-null  object
 5   majorityStatusAtExploit                 9290 non-null   object
 6   majorityEntry                           6491 non-null   object
 7   citizenship                             48523 non-null  object
 8   meansOfControlDebtBondage               2496 non-null   float64
 9   meansOfControlTakesEarnings             3997 non-null   float64
 10  meansOfControlRestrictsFinancialAccess  253 non-null    float64
 11  meansOfControlThreats                   5164 non-null   float64
 12  meansOfControlPsychologicalAbuse        6056 non-null   float64
 13  meansOfControlPhysicalAbuse             4849 non-null   float64
 14  meansOfControlSexualAbuse               2821 non-null   float64
 15  meansOfControlFalsePromises             3840 non-null   float64
 16  meansOfControlPsychoactiveSubstances    3509 non-null   float64
 17  meansOfControlRestrictsMovement         5620 non-null   float64
 18  meansOfControlRestrictsMedicalCare      2499 non-null   float64
 19  meansOfControlExcessiveWorkingHours     3317 non-null   float64
 20  meansOfControlUsesChildren              151 non-null    float64
 21  meansOfControlThreatOfLawEnforcement    2008 non-null   float64
 22  meansOfControlWithholdsNecessities      2584 non-null   float64
 23  meansOfControlWithholdsDocuments        3274 non-null   float64
 24  meansOfControlOther                     3100 non-null   float64
 25  meansOfControlNotSpecified              36857 non-null  float64
 26  meansOfControlConcatenated              16520 non-null  object
 27  isForcedLabour                          26102 non-null  float64
 28  isSexualExploit                         23861 non-null  float64
 29  isOtherExploit                          30938 non-null  float64
 30  isSexAndLabour                          23456 non-null  float64
 31  isForcedMarriage                        11026 non-null  float64
 32  isForcedMilitary                        11450 non-null  float64
 33  isOrganRemoval                          11450 non-null  float64
 34  isSlaveryAndPractices                   1588 non-null   float64
 35  typeOfExploitConcatenated               32627 non-null  object
 36  typeOfLabourAgriculture                 20472 non-null  float64
 37  typeOfLabourAquafarming                 20433 non-null  float64
 38  typeOfLabourBegging                     20420 non-null  float64
 39  typeOfLabourConstruction                20800 non-null  float64
 40  typeOfLabourDomesticWork                22551 non-null  float64
 41  typeOfLabourHospitality                 21681 non-null  float64
 42  typeOfLabourIllicitActivities           20342 non-null  float64
 43  typeOfLabourManufacturing               20545 non-null  float64
 44  typeOfLabourMiningOrDrilling            20420 non-null  float64
 45  typeOfLabourPeddling                    20342 non-null  float64
 46  typeOfLabourTransportation              20420 non-null  float64
 47  typeOfLabourOther                       21684 non-null  float64
 48  typeOfLabourNotSpecified                21622 non-null  float64
 49  typeOfLabourConcatenated                6249 non-null   object
 50  typeOfSexProstitution                   18458 non-null  float64
 51  typeOfSexPornography                    6444 non-null   float64
 52  typeOfSexRemoteInteractiveServices      6444 non-null   float64
 53  typeOfSexPrivateSexualServices          5215 non-null   float64
 54  typeOfSexConcatenated                   4589 non-null   object
 55  isAbduction                             16371 non-null  float64
 56  RecruiterRelationship                   18120 non-null  object
 57  CountryOfExploitation                   38626 non-null  object
 58  recruiterRelationIntimatePartner        39994 non-null  float64
 59  recruiterRelationFriend                 39994 non-null  float64
 60  recruiterRelationFamily                 39994 non-null  float64
 61  recruiterRelationOther                  39994 non-null  float64
 62  recruiterRelationUnknown                48724 non-null  float64
dtypes: float64(49), int64(1), object(13)
memory usage: 23.5+ MB

In [9]:
# let's get just the US entries
us_df = df.loc[df["CountryOfExploitation"] == "US"]
us_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12512 entries, 18589 to 48772
Data columns (total 63 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   yearOfRegistration                      12512 non-null  int64
 1   Datasource                              12512 non-null  object
 2   gender                                  12512 non-null  object
 3   ageBroad                                12512 non-null  object
 4   majorityStatus                          12512 non-null  object
 5   majorityStatusAtExploit                 7235 non-null   object
 6   majorityEntry                           558 non-null    object
 7   citizenship                             12512 non-null  object
 8   meansOfControlDebtBondage               403 non-null    float64
 9   meansOfControlTakesEarnings             801 non-null    float64
 10  meansOfControlRestrictsFinancialAccess  116 non-null    float64
 11  meansOfControlThreats                   2264 non-null   float64
 12  meansOfControlPsychologicalAbuse        2811 non-null   float64
 13  meansOfControlPhysicalAbuse             2268 non-null   float64
 14  meansOfControlSexualAbuse               1204 non-null   float64
 15  meansOfControlFalsePromises             341 non-null    float64
 16  meansOfControlPsychoactiveSubstances    2106 non-null   float64
 17  meansOfControlRestrictsMovement         2473 non-null   float64
 18  meansOfControlRestrictsMedicalCare      88 non-null     float64
 19  meansOfControlExcessiveWorkingHours     76 non-null     float64
 20  meansOfControlUsesChildren              120 non-null    float64
 21  meansOfControlThreatOfLawEnforcement    99 non-null     float64
 22  meansOfControlWithholdsNecessities      507 non-null    float64
 23  meansOfControlWithholdsDocuments        253 non-null    float64
 24  meansOfControlOther                     1668 non-null   float64
 25  meansOfControlNotSpecified              12512 non-null  float64
 26  meansOfControlConcatenated              12503 non-null  object
 27  isForcedLabour                          12006 non-null  float64
 28  isSexualExploit                         12006 non-null  float64
 29  isOtherExploit                          12512 non-null  float64
 30  isSexAndLabour                          12006 non-null  float64
 31  isForcedMarriage                        0 non-null      float64
 32  isForcedMilitary                        0 non-null      float64
 33  isOrganRemoval                          0 non-null      float64
 34  isSlaveryAndPractices                   0 non-null      float64
 35  typeOfExploitConcatenated               12006 non-null  object
 36  typeOfLabourAgriculture                 12466 non-null  float64
 37  typeOfLabourAquafarming                 12466 non-null  float64
 38  typeOfLabourBegging                     12466 non-null  float64
 39  typeOfLabourConstruction                12466 non-null  float64
 40  typeOfLabourDomesticWork                12466 non-null  float64
 41  typeOfLabourHospitality                 12466 non-null  float64
 42  typeOfLabourIllicitActivities           12466 non-null  float64
 43  typeOfLabourManufacturing               12466 non-null  float64
 44  typeOfLabourMiningOrDrilling            12466 non-null  float64
 45  typeOfLabourPeddling                    12466 non-null  float64
 46  typeOfLabourTransportation              12466 non-null  float64
 47  typeOfLabourOther                       12466 non-null  float64
 48  typeOfLabourNotSpecified                12512 non-null  float64
 49  typeOfLabourConcatenated                197 non-null    object
 50  typeOfSexProstitution                   5215 non-null   float64
 51  typeOfSexPornography                    5215 non-null   float64
 52  typeOfSexRemoteInteractiveServices      5215 non-null   float64
 53  typeOfSexPrivateSexualServices          5215 non-null   float64
 54  typeOfSexConcatenated                   4558 non-null   object
 55  isAbduction                             3965 non-null   float64
 56  RecruiterRelationship                   12512 non-null  object
 57  CountryOfExploitation                   12512 non-null  object
 58  recruiterRelationIntimatePartner        3782 non-null   float64
 59  recruiterRelationFriend                 3782 non-null   float64
 60  recruiterRelationFamily                 3782 non-null   float64
 61  recruiterRelationOther                  3782 non-null   float64
 62  recruiterRelationUnknown                12512 non-null  float64
dtypes: float64(49), int64(1), object(13)
memory usage: 6.1+ MB

Based on the number and names of columns, there is already some categorical encoding going on! I'll sepearate them out and get a better idea of missingness.

In [10]:
us_df.iloc[:, 0:8]

,yearOfRegistration,Datasource,gender,ageBroad,majorityStatus,majorityStatusAtExploit,majorityEntry,citizenship
18589,2015,Hotline,Female,18--20,Adult,Adult,NaN,00
18590,2015,Hotline,Female,18--20,Adult,NaN,NaN,00
18591,2015,Hotline,Female,18--20,Adult,Minor,Adult,00
18592,2015,Hotline,Female,18--20,Adult,NaN,NaN,00
18593,2015,Hotline,Female,18--20,Adult,Minor,NaN,00
...,...,...,...,...,...,...,...,...
48768,2018,Hotline,Male,9--17,Minor,Minor,NaN,US
48769,2018,Hotline,Male,9--17,Minor,Minor,NaN,US
48770,2018,Hotline,Male,9--17,Minor,Minor,NaN,US
48771,2018,Hotline,Male,9--17,Minor,Minor,NaN,US
48772,2018,Hotline,Male,9--17,Minor,Minor,Minor,US

In [11]:
concat_cols = us_df.filter(like="Concat", axis=1)
concat_cols

,meansOfControlConcatenated,typeOfExploitConcatenated,typeOfLabourConcatenated,typeOfSexConcatenated
18589,Takes earnings;Psychological abuse;Physical ab...,Sexual exploitation,NaN,Prostitution
18590,Threats;Psychoactive substances;Restricts medi...,Sexual exploitation,NaN,Prostitution
18591,Restricts movement,Sexual exploitation,NaN,Prostitution
18592,Psychological abuse;Psychoactive substances;Re...,Sexual exploitation,NaN,Prostitution
18593,Restricts movement;Withholds necessities,Sexual exploitation,NaN,Prostitution
...,...,...,...,...
48768,Psychological abuse,Sexual exploitation,NaN,NaN
48769,Threats;Psychological abuse;Physical abuse,Sexual exploitation,NaN,NaN
48770,Threats;Psychological abuse;Physical abuse,Sexual exploitation,NaN,NaN
48771,Not specified,Sexual exploitation,NaN,NaN
48772,Psychological abuse;Physical abuse;Sexual abuse,Sexual exploitation,NaN,NaN

In [12]:
concat_cols.isna().sum()

meansOfControlConcatenated        9
typeOfExploitConcatenated       506
typeOfLabourConcatenated      12315
typeOfSexConcatenated          7954
dtype: int64

In [13]:
concat_cols["typeOfLabourConcatenated"].value_counts()

Peddling         58
Other            52
Not specified    46
Begging          22
Agriculture      19
Name: typeOfLabourConcatenated, dtype: int64

In [27]:
us_df["typeOfExploitConcatenated"].value_counts(dropna=False)

Sexual exploitation                                                          11809
NaN                                                                            506
Forced labour                                                                  151
Forced labour;Sexual exploitation;Combined sexual and labour exploitation       46
Name: typeOfExploitConcatenated, dtype: int64

In [14]:
us_df.filter(like="Labour", axis=1).isna().sum()

isForcedLabour                     506
isSexAndLabour                     506
typeOfLabourAgriculture             46
typeOfLabourAquafarming             46
typeOfLabourBegging                 46
typeOfLabourConstruction            46
typeOfLabourDomesticWork            46
typeOfLabourHospitality             46
typeOfLabourIllicitActivities       46
typeOfLabourManufacturing           46
typeOfLabourMiningOrDrilling        46
typeOfLabourPeddling                46
typeOfLabourTransportation          46
typeOfLabourOther                   46
typeOfLabourNotSpecified             0
typeOfLabourConcatenated         12315
dtype: int64

In [15]:
for col in us_df.columns:
    print(f"Column: {col}:")
    print(us_df[col].value_counts(dropna=False))
    print("----------")

Column: yearOfRegistration:
2018    4182
2017    3683
2016    3188
2015    1459
Name: yearOfRegistration, dtype: int64
----------
Column: Datasource:
Hotline    12512
Name: Datasource, dtype: int64
----------
Column: gender:
Female    12168
Male        344
Name: gender, dtype: int64
----------
Column: ageBroad:
9--17     4992
18--20    2138
21--23    1492
30--38    1388
24--26    1069
27--29     707
39--47     403
48+        167
0--8       156
Name: ageBroad, dtype: int64
----------
Column: majorityStatus:
Adult    7364
Minor    5148
Name: majorityStatus, dtype: int64
----------
Column: majorityStatusAtExploit:
Minor    6142
NaN      5277
Adult    1093
Name: majorityStatusAtExploit, dtype: int64
----------
Column: majorityEntry:
NaN      11954
Minor      283
Adult      275
Name: majorityEntry, dtype: int64
----------
Column: citizenship:
00    8822
US    3636
CN      23
MX      19
KR      12
Name: citizenship, dtype: int64
----------
Column: meansOfControlDebtBondage:
NaN    12109
1.0      403
Name: meansOfControlDebtBondage, dtype: int64
----------
Column: meansOfControlTakesEarnings:
NaN    11711
1.0      801
Name: meansOfControlTakesEarnings, dtype: int64
----------
Column: meansOfControlRestrictsFinancialAccess:
NaN    12396
1.0      116
Name: meansOfControlRestrictsFinancialAccess, dtype: int64
----------
Column: meansOfControlThreats:
NaN    10248
1.0     2264
Name: meansOfControlThreats, dtype: int64
----------
Column: meansOfControlPsychologicalAbuse:
NaN    9701
1.0    2811
Name: meansOfControlPsychologicalAbuse, dtype: int64
----------
Column: meansOfControlPhysicalAbuse:
NaN    10244
1.0     2268
Name: meansOfControlPhysicalAbuse, dtype: int64
----------
Column: meansOfControlSexualAbuse:
NaN    11308
1.0     1204
Name: meansOfControlSexualAbuse, dtype: int64
----------
Column: meansOfControlFalsePromises:
NaN    12171
1.0      341
Name: meansOfControlFalsePromises, dtype: int64
----------
Column: meansOfControlPsychoactiveSubstances:
NaN    10406
1.0     2106
Name: meansOfControlPsychoactiveSubstances, dtype: int64
----------
Column: meansOfControlRestrictsMovement:
NaN    10039
1.0     2473
Name: meansOfControlRestrictsMovement, dtype: int64
----------
Column: meansOfControlRestrictsMedicalCare:
NaN    12424
1.0       88
Name: meansOfControlRestrictsMedicalCare, dtype: int64
----------
Column: meansOfControlExcessiveWorkingHours:
NaN    12436
1.0       76
Name: meansOfControlExcessiveWorkingHours, dtype: int64
----------
Column: meansOfControlUsesChildren:
NaN    12392
1.0      120
Name: meansOfControlUsesChildren, dtype: int64
----------
Column: meansOfControlThreatOfLawEnforcement:
NaN    12413
1.0       99
Name: meansOfControlThreatOfLawEnforcement, dtype: int64
----------
Column: meansOfControlWithholdsNecessities:
NaN    12005
1.0      507
Name: meansOfControlWithholdsNecessities, dtype: int64
----------
Column: meansOfControlWithholdsDocuments:
NaN    12259
1.0      253
Name: meansOfControlWithholdsDocuments, dtype: int64
----------
Column: meansOfControlOther:
NaN    10844
1.0     1668
Name: meansOfControlOther, dtype: int64
----------
Column: meansOfControlNotSpecified:
0.0    7317
1.0    5195
Name: meansOfControlNotSpecified, dtype: int64
----------
Column: meansOfControlConcatenated:
Not specified                                                                                                                   5195
Psychological abuse                                                                                                              749
Restricts movement                                                                                                               501
Psychoactive substances                                                                                                          455
Threats                                                                                                                          288
                                                                                                                                ...
Debt bondage;Takes earnings;Psychological abuse;Sexual abuse;False promises;Restricts movement;Excessive working hours;Other       1
Threats;Psychological abuse;Restricts movement;Threat of law enforcement                                                           1
Takes earnings;Threats;Psychological abuse;Physical abuse;Restricts movement;Withholds necessities;Other                           1
Debt bondage;Psychoactive substances;Other                                                                                         1
Psychological abuse;Physical abuse;Uses children                                                                                   1
Name: meansOfControlConcatenated, Length: 1045, dtype: int64
----------
Column: isForcedLabour:
0.0    11809
NaN      506
1.0      197
Name: isForcedLabour, dtype: int64
----------
Column: isSexualExploit:
1.0    11855
NaN      506
0.0      151
Name: isSexualExploit, dtype: int64
----------
Column: isOtherExploit:
0.0    12512
Name: isOtherExploit, dtype: int64
----------
Column: isSexAndLabour:
0.0    11960
NaN      506
1.0       46
Name: isSexAndLabour, dtype: int64
----------
Column: isForcedMarriage:
NaN    12512
Name: isForcedMarriage, dtype: int64
----------
Column: isForcedMilitary:
NaN    12512
Name: isForcedMilitary, dtype: int64
----------
Column: isOrganRemoval:
NaN    12512
Name: isOrganRemoval, dtype: int64
----------
Column: isSlaveryAndPractices:
NaN    12512
Name: isSlaveryAndPractices, dtype: int64
----------
Column: typeOfExploitConcatenated:
Sexual exploitation                                                          11809
NaN                                                                            506
Forced labour                                                                  151
Forced labour;Sexual exploitation;Combined sexual and labour exploitation       46
Name: typeOfExploitConcatenated, dtype: int64
----------
Column: typeOfLabourAgriculture:
0.0    12447
NaN       46
1.0       19
Name: typeOfLabourAgriculture, dtype: int64
----------
Column: typeOfLabourAquafarming:
0.0    12466
NaN       46
Name: typeOfLabourAquafarming, dtype: int64
----------
Column: typeOfLabourBegging:
0.0    12444
NaN       46
1.0       22
Name: typeOfLabourBegging, dtype: int64
----------
Column: typeOfLabourConstruction:
0.0    12466
NaN       46
Name: typeOfLabourConstruction, dtype: int64
----------
Column: typeOfLabourDomesticWork:
0.0    12466
NaN       46
Name: typeOfLabourDomesticWork, dtype: int64
----------
Column: typeOfLabourHospitality:
0.0    12466
NaN       46
Name: typeOfLabourHospitality, dtype: int64
----------
Column: typeOfLabourIllicitActivities:
0.0    12466
NaN       46
Name: typeOfLabourIllicitActivities, dtype: int64
----------
Column: typeOfLabourManufacturing:
0.0    12466
NaN       46
Name: typeOfLabourManufacturing, dtype: int64
----------
Column: typeOfLabourMiningOrDrilling:
0.0    12466
NaN       46
Name: typeOfLabourMiningOrDrilling, dtype: int64
----------
Column: typeOfLabourPeddling:
0.0    12408
1.0       58
NaN       46
Name: typeOfLabourPeddling, dtype: int64
----------
Column: typeOfLabourTransportation:
0.0    12466
NaN       46
Name: typeOfLabourTransportation, dtype: int64
----------
Column: typeOfLabourOther:
0.0    12414
1.0       52
NaN       46
Name: typeOfLabourOther, dtype: int64
----------
Column: typeOfLabourNotSpecified:
0.0    12466
1.0       46
Name: typeOfLabourNotSpecified, dtype: int64
----------
Column: typeOfLabourConcatenated:
NaN              12315
Peddling            58
Other               52
Not specified       46
Begging             22
Agriculture         19
Name: typeOfLabourConcatenated, dtype: int64
----------
Column: typeOfSexProstitution:
NaN    7297
1.0    4369
0.0     846
Name: typeOfSexProstitution, dtype: int64
----------
Column: typeOfSexPornography:
NaN    7297
0.0    5069
1.0     146
Name: typeOfSexPornography, dtype: int64
----------
Column: typeOfSexRemoteInteractiveServices:
NaN    7297
0.0    5215
Name: typeOfSexRemoteInteractiveServices, dtype: int64
----------
Column: typeOfSexPrivateSexualServices:
NaN    7297
0.0    5172
1.0      43
Name: typeOfSexPrivateSexualServices, dtype: int64
----------
Column: typeOfSexConcatenated:
NaN                        7954
Prostitution               4369
Pornography                 146
Private sexual services      43
Name: typeOfSexConcatenated, dtype: int64
----------
Column: isAbduction:
NaN    8547
0.0    3926
1.0      39
Name: isAbduction, dtype: int64
----------
Column: RecruiterRelationship:
Not Specified                                           8730
Intimate Partner                                        1503
Family/Relative                                          985
Other                                                    622
Friend/Acquaintance                                      431
Friend/Acquaintance; Other                                51
Family/Relative; Intimate Partner                         41
Intimate Partner; Other                                   39
Friend/Acquaintance; Intimate Partner                     28
Not Specified; Other                                      24
Family/Relative; Other                                    18
Family/Relative; Friend/Acquaintance                      16
Family/Relative; Not Specified                             8
Intimate Partner; Not Specified                            6
Friend/Acquaintance; Intimate Partner; Other               4
Family/Relative; Friend/Acquaintance; Other                2
Friend/Acquaintance; Intimate Partner; Not Specified       1
Family/Relative; Intimate Partner; Other                   1
Friend/Acquaintance; Not Specified; Other                  1
Friend/Acquaintance; Not Specified                         1
Name: RecruiterRelationship, dtype: int64
----------
Column: CountryOfExploitation:
US    12512
Name: CountryOfExploitation, dtype: int64
----------
Column: recruiterRelationIntimatePartner:
NaN    8730
0.0    2159
1.0    1623
Name: recruiterRelationIntimatePartner, dtype: int64
----------
Column: recruiterRelationFriend:
NaN    8730
0.0    3247
1.0     535
Name: recruiterRelationFriend, dtype: int64
----------
Column: recruiterRelationFamily:
NaN    8730
0.0    2711
1.0    1071
Name: recruiterRelationFamily, dtype: int64
----------
Column: recruiterRelationOther:
NaN    8730
0.0    3020
1.0     762
Name: recruiterRelationOther, dtype: int64
----------
Column: recruiterRelationUnknown:
1.0    8771
0.0    3741
Name: recruiterRelationUnknown, dtype: int64
----------

In [16]:
us_df.shape

(12512, 63)

In [17]:
empty_cols = []

for col in us_df.columns:
    if us_df[col].isna().sum() == us_df.shape[0]:
        print(col)
        empty_cols.append(col)

isForcedMarriage
isForcedMilitary
isOrganRemoval
isSlaveryAndPractices

In [18]:
# drop all columns where every value is missing
empty_cols = []
for col in us_df.columns:
    if us_df[col].isna().sum() == us_df.shape[0]:
        print(col)
        empty_cols.append(col)


us_df = us_df.drop(columns=empty_cols)
us_df.shape

# the columns with all nan's are things I would like to think don't occur because we selected the USA.
# In reality, the people with the resources to force marriage, military service, organ removal or slavery
# are too powerful to get caught. Unlikely this just doesn't happen in the USA
# these acts are more deadly than the remaining categories. Might be why no reports...

isForcedMarriage
isForcedMilitary
isOrganRemoval
isSlaveryAndPractices

(12512, 59)

In [19]:
us_df.columns

Index(['yearOfRegistration', 'Datasource', 'gender', 'ageBroad',
       'majorityStatus', 'majorityStatusAtExploit', 'majorityEntry',
       'citizenship', 'meansOfControlDebtBondage',
       'meansOfControlTakesEarnings', 'meansOfControlRestrictsFinancialAccess',
       'meansOfControlThreats', 'meansOfControlPsychologicalAbuse',
       'meansOfControlPhysicalAbuse', 'meansOfControlSexualAbuse',
       'meansOfControlFalsePromises', 'meansOfControlPsychoactiveSubstances',
       'meansOfControlRestrictsMovement', 'meansOfControlRestrictsMedicalCare',
       'meansOfControlExcessiveWorkingHours', 'meansOfControlUsesChildren',
       'meansOfControlThreatOfLawEnforcement',
       'meansOfControlWithholdsNecessities',
       'meansOfControlWithholdsDocuments', 'meansOfControlOther',
       'meansOfControlNotSpecified', 'meansOfControlConcatenated',
       'isForcedLabour', 'isSexualExploit', 'isOtherExploit', 'isSexAndLabour',
       'typeOfExploitConcatenated', 'typeOfLabourAgriculture',
       'typeOfLabourAquafarming', 'typeOfLabourBegging',
       'typeOfLabourConstruction', 'typeOfLabourDomesticWork',
       'typeOfLabourHospitality', 'typeOfLabourIllicitActivities',
       'typeOfLabourManufacturing', 'typeOfLabourMiningOrDrilling',
       'typeOfLabourPeddling', 'typeOfLabourTransportation',
       'typeOfLabourOther', 'typeOfLabourNotSpecified',
       'typeOfLabourConcatenated', 'typeOfSexProstitution',
       'typeOfSexPornography', 'typeOfSexRemoteInteractiveServices',
       'typeOfSexPrivateSexualServices', 'typeOfSexConcatenated',
       'isAbduction', 'RecruiterRelationship', 'CountryOfExploitation',
       'recruiterRelationIntimatePartner', 'recruiterRelationFriend',
       'recruiterRelationFamily', 'recruiterRelationOther',
       'recruiterRelationUnknown'],
      dtype='object')

In [20]:
us_df.filter(like="is", axis=1).columns

Index(['yearOfRegistration', 'meansOfControlFalsePromises', 'isForcedLabour',
       'isSexualExploit', 'isOtherExploit', 'isSexAndLabour', 'isAbduction'],
      dtype='object')

In [21]:
# investigate missingness and clean by column category
# if a concat col has an NA, then we should expect that row to be 0 for all related cols
control_columns = us_df.filter(like="Control", axis=1).columns
labour_type_columns = us_df.filter(like="Labour", axis=1).columns
sex_columns = us_df.filter(like="Sex", axis=1).columns
recruiter_columns = us_df.filter(like="Recruiter", axis=1).columns

demogr_columns = [
    "yearOfRegistration",
    "Datasource",
    "gender",
    "ageBroad",
    "citizenship",
    "CountryOfExploitation",
    "majorityStatus",
    "majorityStatusAtExploit",
    "majorityEntry",
]

In [38]:
control_df[control_df["meansOfControlConcatenated"].isna()]

,meansOfControlDebtBondage,meansOfControlTakesEarnings,meansOfControlRestrictsFinancialAccess,meansOfControlThreats,meansOfControlPsychologicalAbuse,meansOfControlPhysicalAbuse,meansOfControlSexualAbuse,meansOfControlFalsePromises,meansOfControlPsychoactiveSubstances,meansOfControlRestrictsMovement,meansOfControlRestrictsMedicalCare,meansOfControlExcessiveWorkingHours,meansOfControlUsesChildren,meansOfControlThreatOfLawEnforcement,meansOfControlWithholdsNecessities,meansOfControlWithholdsDocuments,meansOfControlOther,meansOfControlNotSpecified,meansOfControlConcatenated
19199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
19362,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
19492,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
19582,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
19670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
19688,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
33341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
35693,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN
35943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN

In [22]:
# investigate control cols
# make sure there the concat col and indiv cols agree on options

pd.options.display.max_columns = 999

# us_df[control_columns].isna().all(axis=1).sum()
control_df = us_df[control_columns]
control_df["meansOfControlConcatenated"].str.split(pat=";").explode().nunique()
# there are 18 options in the control-concat col, same as num of indiv control cols
print(control_df["meansOfControlConcatenated"].str.split(pat=";").explode().unique())
print(control_df.columns.sort_values())
# evaluated manually, but the options are equivalent

# where control-concat was nan, all others were nan
# save these rows for now to see if this pattern is associated with other missing patterns

missing_all_control_indices = control_df[
    control_df["meansOfControlConcatenated"].isna()
].index


# do this for each category!

['Takes earnings' 'Psychological abuse' 'Physical abuse'
 'Psychoactive substances' 'Threats' 'Restricts medical care'
 'Restricts movement' 'Withholds necessities' 'False promises'
 'Debt bondage' 'Withholds documents' 'Other' 'Sexual abuse'
 'Not specified' 'Uses children' 'Threat of law enforcement'
 'Restricts financial access' 'Excessive working hours' nan]
Index(['meansOfControlConcatenated', 'meansOfControlDebtBondage',
       'meansOfControlExcessiveWorkingHours', 'meansOfControlFalsePromises',
       'meansOfControlNotSpecified', 'meansOfControlOther',
       'meansOfControlPhysicalAbuse', 'meansOfControlPsychoactiveSubstances',
       'meansOfControlPsychologicalAbuse',
       'meansOfControlRestrictsFinancialAccess',
       'meansOfControlRestrictsMedicalCare', 'meansOfControlRestrictsMovement',
       'meansOfControlSexualAbuse', 'meansOfControlTakesEarnings',
       'meansOfControlThreatOfLawEnforcement', 'meansOfControlThreats',
       'meansOfControlUsesChildren', 'meansOfControlWithholdsDocuments',
       'meansOfControlWithholdsNecessities'],
      dtype='object')

In [34]:
labour_df = us_df[labour_type_columns]
labour_df = labour_df.drop(columns=["isForcedLabour", "isSexAndLabour"])
labour_df.columns
labour_df["typeOfLabourConcatenated"].str.split(pat=";").explode().nunique()

print(labour_df["typeOfLabourConcatenated"].str.split(pat=";").explode().unique())
print(labour_df.columns.sort_values())

[nan 'Other' 'Peddling' 'Begging' 'Not specified' 'Agriculture']
Index(['typeOfLabourAgriculture', 'typeOfLabourAquafarming',
       'typeOfLabourBegging', 'typeOfLabourConcatenated',
       'typeOfLabourConstruction', 'typeOfLabourDomesticWork',
       'typeOfLabourHospitality', 'typeOfLabourIllicitActivities',
       'typeOfLabourManufacturing', 'typeOfLabourMiningOrDrilling',
       'typeOfLabourNotSpecified', 'typeOfLabourOther', 'typeOfLabourPeddling',
       'typeOfLabourTransportation'],
      dtype='object')

In [ ]:
labour_df = us_df[labour_type_columns]
labour_df_df["meansOfControlConcatenated"].str.split(pat=";").explode().nunique()
# there are 18 options in the control-concat col, same as num of indiv control cols
print(control_df["meansOfControlConcatenated"].str.split(pat=";").explode().unique())
print(control_df.columns.sort_values())
# evaluated manually, but the options are equivalent

# where control-concat was nan, all others were nan
# save these rows for now to see if this pattern is associated with other missing patterns

missing_all_control_indices = control_df[
    control_df["meansOfControlConcatenated"].isna()
].index

In [35]:
us_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12512 entries, 18589 to 48772
Data columns (total 59 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   yearOfRegistration                      12512 non-null  int64
 1   Datasource                              12512 non-null  object
 2   gender                                  12512 non-null  object
 3   ageBroad                                12512 non-null  object
 4   majorityStatus                          12512 non-null  object
 5   majorityStatusAtExploit                 7235 non-null   object
 6   majorityEntry                           558 non-null    object
 7   citizenship                             12512 non-null  object
 8   meansOfControlDebtBondage               403 non-null    float64
 9   meansOfControlTakesEarnings             801 non-null    float64
 10  meansOfControlRestrictsFinancialAccess  116 non-null    float64
 11  meansOfControlThreats                   2264 non-null   float64
 12  meansOfControlPsychologicalAbuse        2811 non-null   float64
 13  meansOfControlPhysicalAbuse             2268 non-null   float64
 14  meansOfControlSexualAbuse               1204 non-null   float64
 15  meansOfControlFalsePromises             341 non-null    float64
 16  meansOfControlPsychoactiveSubstances    2106 non-null   float64
 17  meansOfControlRestrictsMovement         2473 non-null   float64
 18  meansOfControlRestrictsMedicalCare      88 non-null     float64
 19  meansOfControlExcessiveWorkingHours     76 non-null     float64
 20  meansOfControlUsesChildren              120 non-null    float64
 21  meansOfControlThreatOfLawEnforcement    99 non-null     float64
 22  meansOfControlWithholdsNecessities      507 non-null    float64
 23  meansOfControlWithholdsDocuments        253 non-null    float64
 24  meansOfControlOther                     1668 non-null   float64
 25  meansOfControlNotSpecified              12512 non-null  float64
 26  meansOfControlConcatenated              12503 non-null  object
 27  isForcedLabour                          12006 non-null  float64
 28  isSexualExploit                         12006 non-null  float64
 29  isOtherExploit                          12512 non-null  float64
 30  isSexAndLabour                          12006 non-null  float64
 31  typeOfExploitConcatenated               12006 non-null  object
 32  typeOfLabourAgriculture                 12466 non-null  float64
 33  typeOfLabourAquafarming                 12466 non-null  float64
 34  typeOfLabourBegging                     12466 non-null  float64
 35  typeOfLabourConstruction                12466 non-null  float64
 36  typeOfLabourDomesticWork                12466 non-null  float64
 37  typeOfLabourHospitality                 12466 non-null  float64
 38  typeOfLabourIllicitActivities           12466 non-null  float64
 39  typeOfLabourManufacturing               12466 non-null  float64
 40  typeOfLabourMiningOrDrilling            12466 non-null  float64
 41  typeOfLabourPeddling                    12466 non-null  float64
 42  typeOfLabourTransportation              12466 non-null  float64
 43  typeOfLabourOther                       12466 non-null  float64
 44  typeOfLabourNotSpecified                12512 non-null  float64
 45  typeOfLabourConcatenated                197 non-null    object
 46  typeOfSexProstitution                   5215 non-null   float64
 47  typeOfSexPornography                    5215 non-null   float64
 48  typeOfSexRemoteInteractiveServices      5215 non-null   float64
 49  typeOfSexPrivateSexualServices          5215 non-null   float64
 50  typeOfSexConcatenated                   4558 non-null   object
 51  isAbduction                             3965 non-null   float64
 52  RecruiterRelationship                   12512 non-null  object
 53  CountryOfExploitation                   12512 non-null  object
 54  recruiterRelationIntimatePartner        3782 non-null   float64
 55  recruiterRelationFriend                 3782 non-null   float64
 56  recruiterRelationFamily                 3782 non-null   float64
 57  recruiterRelationOther                  3782 non-null   float64
 58  recruiterRelationUnknown                12512 non-null  float64
dtypes: float64(45), int64(1), object(13)
memory usage: 5.7+ MB